openapi: 3.0.3
info:
  title: Receita Federal Mock API
  version: 1.0.0
  description: API mock para consulta de CNPJ utilizada no desafio de integração Salesforce.

servers:
  - url: https://api.receita.mock

paths:
  /cnpj/{cnpj}:
    get:
      summary: Consulta dados cadastrais de um CNPJ
      operationId: Consultar_CNPJ
      parameters:
        - name: cnpj
          in: path
          required: true
          schema:
            type: string
          description: Número do CNPJ sem pontuação
      responses:
        "200":
          description: Dados encontrados
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CNPJResponse"

        "404":
          description: CNPJ não encontrado
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    CNPJResponse:
      type: object
      properties:
        cnpj:
          type: string
        razao_social:
          type: string
        nome_fantasia:
          type: string
        situacao_cadastral:
          type: string
        regime_tributario:
          type: string
        cnae_principal:
          type: string
        endereco:
          $ref: "#/components/schemas/Endereco"

    Endereco:
      type: object
      properties:
        logradouro:
          type: string
        numero:
          type: string
        complemento:
          type: string
        bairro:
          type: string
        cidade:
          type: string
        estado:
          type: string
        cep:
          type: string

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
